accounts/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import TokenRefreshView

app_name = 'accounts'

urlpatterns = [
    # Server-Side Login and Logout for Web App
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('users/', views.manage_users, name='manage_users'),
    path('users/create/', views.create_user, name='create_user'),
    path('users/<int:user_id>/edit/', views.edit_user, name='edit_user'),
    path('users/<int:user_id>/delete/', views.delete_user, name='delete_user'),

    # API Endpoints for Mobile App
    path('api/login/', views.LoginView.as_view(), name='api-login'),
    path('api/logout/', views.LogoutView.as_view(), name='api-logout'),
    path('api/signup/', views.SignUpView.as_view(), name='api-signup'),
    path('api/profile/', views.UserProfileView.as_view(), name='api-profile'),
    path('api/validate-token/', views.ValidateTokenView.as_view(), name='validate-token'),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/verify_email/", views.verify_email_code, name="verify_email_code"),
    path("api/update_profile/", views.update_profile, name="update_profile"),
]

restaurants/urls.py
from django.urls import path
from . import views

app_name = 'restaurant'

urlpatterns = [
    path('', views.home, name='home'),
    path('restaurant/<int:restaurant_id>/',
         views.restaurant_detail, name='restaurant_detail'),
    path('restaurant/<int:restaurant_id>/save/', views.save_restaurant_details,
         name='save_restaurant_details'),
    path('create/', views.create_restaurant, name='create_restaurant'),
    path('cuisines/', views.manage_cuisines, name='manage_cuisines'),
    path('cuisines/create/', views.create_cuisine, name='create_cuisine'),
    path('cuisines/<int:cuisine_id>/edit/', views.edit_cuisine, name='edit_cuisine'),
    path('cuisines/<int:cuisine_id>/delete/', views.delete_cuisine, name='delete_cuisine'),
    path('delete/<int:restaurant_id>/', views.delete_restaurant, name='delete_restaurant'),
    path('api/restaurants/', views.get_restaurants, name='get_restaurants'),
    path("api/restaurants/<int:restaurant_id>/slots/",
         views.get_available_slots, name="get_available_slots"),
    path("api/restaurants/<int:restaurant_id>/reviews/",
         views.get_reviews, name="get_reviews"),
    path("api/restaurants/<int:restaurant_id>/menu/",
         views.get_menu, name="get_menu"),
    path("api/restaurants/reservations/",
         views.create_reservation, name="create_reservation"),
    path("api/restaurants/<int:restaurant_id>/create_review/",
         views.create_review, name="create_review"),
    path("api/restaurants/delete_review/<int:review_id>/",
         views.delete_review, name="delete_review"),
    path("api/restaurants/saved/", views.get_saved_restaurants,
         name="get_saved_restaurants"),
    path("api/restaurants/saved/details/", views.get_saved_restaurant_details,
         name="get_saved_restaurant_details"),
    path("api/restaurants/saved/<int:restaurant_id>/",
         views.toggle_saved_restaurant, name="toggle_saved_restaurant"),
    path("api/restaurants/cuisines/", views.get_cuisines, name="get_cuisines"),
    path("api/restaurants/recent_bookings/",
         views.get_recent_bookings, name="get_recent_bookings"),
    path("api/restaurants/saved/<int:restaurant_id>/status/",
         views.check_saved_status, name="check_saved_status"),
    path("api/restaurants/user_reservations/",
         views.list_user_reservations, name="user_reservations"),
]

seatify_backend/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('restaurants.urls', namespace='restaurant')),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Seatify{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<header>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-transparent">
        <div class="container-fluid">
            <!-- Logo -->
            <a class="navbar-brand" href="/">
                <img src="{% static 'images/logo.png' %}" alt="Seatify Logo" width="150"
                     class="d-inline-block align-text-top">
            </a>

            <!-- Navbar toggler for mobile -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Navbar Links -->
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    {% if request.user.is_authenticated %}
                        {% if request.user.role == 'super_admin' %}
                            <li class="nav-item">
                                <a class="nav-link"
                                   href="{% url 'restaurant:home' %}">Restaurants</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'restaurant:manage_cuisines' %}">Cuisines</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link"
                                   href="{% url 'accounts:manage_users' %}">Users</a>
                            </li>
                        {% elif request.user.role == 'manager' %}
                            <li class="nav-item">
                                <a class="nav-link"
                                   href="{% url 'restaurant:home' %}">Restaurants</a>
                            </li>
                        {% endif %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown"
                               role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Welcome, {{ request.user.first_name }}
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end"
                                aria-labelledby="userDropdown">
                                <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                                </li>
                            </ul>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:login' %}">Sign In</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>
<main class="container">
    {% block content %}
    {% endblock %}
</main>

<!-- Bootstrap JS -->
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>